# app.py — PaySim Fraud Detector
# Generated by fraud_detection_stage13_14.ipynb  (Stage 14)
# ─────────────────────────────────────────────────────────────────────────────
# Run locally  :  streamlit run app.py
# Pre-requisites (relative to repo root):
#   models/streamlit_bundle.joblib
#   data/sample/demo_transactions.parquet
#   reports/figures/*.png   (optional — app skips missing images gracefully)
# ─────────────────────────────────────────────────────────────────────────────
# Feature set (11 features, must match training order exactly):
#   amount, type_TRANSFER,
#   oldbalanceOrg, newbalanceOrig, oldbalanceDest, newbalanceDest,
#   errorBalanceOrig, errorBalanceDest,
#   flag_orig_zero_after, flag_dest_zero_before, flag_dest_zero_both

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import joblib
import os

# ── Page configuration ────────────────────────────────────────────────────────
st.set_page_config(
    page_title='PaySim Fraud Detector',
    page_icon='\U0001F6A8',
    layout='wide',
    initial_sidebar_state='expanded',
)

BUNDLE_PATH    = 'models/streamlit_bundle.joblib'
DEMO_DATA_PATH = 'data/sample/demo_transactions.parquet'

# ── Caching ───────────────────────────────────────────────────────────────────
# cache_resource : load once, share across ALL users and reruns (read-only model).
# cache_data     : return a copy per caller (mutable DataFrames).

@st.cache_resource
def load_bundle():
    if not os.path.exists(BUNDLE_PATH):
        st.error('Bundle not found: ' + BUNDLE_PATH)
        st.error('Run fraud_detection_stage13_14.ipynb (Stage 13) first.')
        st.stop()
    return joblib.load(BUNDLE_PATH)

@st.cache_data
def load_demo():
    if os.path.exists(DEMO_DATA_PATH):
        return pd.read_parquet(DEMO_DATA_PATH)
    return None

bundle  = load_bundle()
demo_df = load_demo()

model        = bundle['model']
FEATURE_COLS = bundle['feature_cols']
THRESHOLD    = bundle['threshold']
metrics      = bundle.get('metrics', {})
train_stats  = bundle.get('train_stats', {})
shap_ranking = bundle.get('shap_ranking', [])
shap_mean_abs= bundle.get('shap_mean_abs', {})
drift_df     = bundle.get('drift_stream_df')
drift_events = bundle.get('drift_events', [])
inject_idx   = bundle.get('drift_inject_index')

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.title('\U0001F6A8 PaySim Fraud Detector')
    st.caption('XGBoost + ADWIN Drift Monitor')
    st.divider()
    st.markdown('**Model snapshot**')
    st.metric(
        'PR-AUC', f"{metrics.get('pr_auc', 0):.3f}",
        help='Primary metric — not inflated by true negatives',
    )
    st.metric(
        'Recall', f"{metrics.get('recall', 0):.1%}",
        help='% of all real frauds caught at the tuned threshold',
    )
    st.metric(
        'Threshold', f'{THRESHOLD:.3f}',
        help='Cost-tuned: FN=$500 / FP=$10 (Stage 10)',
    )
    st.divider()
    st.caption('Created  : ' + bundle.get('created_at', 'N/A')[:10])
    st.caption('XGBoost  : ' + bundle.get('xgboost_version', 'N/A'))
    st.caption('sklearn  : ' + bundle.get('sklearn_version', 'N/A'))
    st.divider()
    st.markdown('**Feature set (' + str(len(FEATURE_COLS)) + ' features)**')
    for f in FEATURE_COLS:
        st.caption('• ' + f)

# ── Tabs ──────────────────────────────────────────────────────────────────────
tab1, tab2, tab3 = st.tabs([
    '\U0001F50D Score a Transaction',
    '\U0001F4CA Model Performance',
    '\U0001F4E1 Drift Monitor',
])

# ==========================================================================
# TAB 1 — Live Transaction Scorer
# ==========================================================================
with tab1:
    st.header('Score a Transaction')
    st.markdown(
        'Enter the six raw transaction fields. All engineered features '
        '(balance errors, zero-balance flags, transaction type flag) '
        'are computed automatically before the model scores the transaction.'
    )

    # Default values pre-set to a classic PaySim fraud signature:
    #   Large TRANSFER, origin drained beyond the transfer amount,
    #   destination balance zero both before and after.
    #   This means on first click the form should return a FRAUD flag.
    with st.form('score_form'):
        c1, c2 = st.columns(2)
        with c1:
            txn_type = st.selectbox(
                'Transaction Type', ['TRANSFER', 'CASH_OUT'],
                help='Fraud only occurs in TRANSFER and CASH_OUT transactions.',
            )
            amount = st.number_input(
                'Amount', min_value=0.0, value=55_000.0, step=1_000.0,
            )
        with c2:
            old_bal_orig = st.number_input(
                'Origin Balance BEFORE',
                min_value=0.0, value=100_000.0, step=1_000.0,
                help='oldbalanceOrg — sender account balance before transfer',
            )
            new_bal_orig = st.number_input(
                'Origin Balance AFTER',
                min_value=0.0, value=0.0, step=1_000.0,
                help='newbalanceOrig — sender account balance after transfer',
            )
            old_bal_dest = st.number_input(
                'Destination Balance BEFORE',
                min_value=0.0, value=0.0, step=1_000.0,
                help='oldbalanceDest — receiver account balance before transfer',
            )
            new_bal_dest = st.number_input(
                'Destination Balance AFTER',
                min_value=0.0, value=0.0, step=1_000.0,
                help='newbalanceDest — receiver account balance after transfer',
            )

        submitted = st.form_submit_button(
            '\U0001F50D Score Transaction', use_container_width=True,
        )

    if submitted:
        # ── Compute all engineered features ──────────────────────────────────
        # These must exactly mirror Stage 5's feature engineering pipeline.
        #
        # errorBalanceOrig: money the origin lost beyond the stated amount.
        #   For a legitimate transfer: (oldbalanceOrg - amount) == newbalanceOrig
        #   so errorBalanceOrig == 0.  A large negative value means the origin
        #   lost more than it should have.
        #
        # errorBalanceDest: money the destination should have gained but did not.
        #   For a legitimate transfer: (oldbalanceDest + amount) == newbalanceDest
        #   so errorBalanceDest == 0.  A large positive value means the destination
        #   never received the money — a hallmark of PaySim fraud.
        #
        # flag_orig_zero_after  : origin account drained to exactly zero.
        # flag_dest_zero_before : destination account was empty before receipt.
        # flag_dest_zero_both   : destination was empty both before and after
        #                         (money passed straight through or never arrived).

        err_orig           = float(new_bal_orig + amount - old_bal_orig)
        err_dest           = float(old_bal_dest + amount - new_bal_dest)
        flag_orig_zero_after   = int(new_bal_orig == 0.0)
        flag_dest_zero_before  = int(old_bal_dest == 0.0)
        flag_dest_zero_both    = int(old_bal_dest == 0.0 and new_bal_dest == 0.0)
        type_transfer          = int(txn_type == 'TRANSFER')

        # Build feature row — order enforced by bundle's feature_cols list.
        # Never rely on dict insertion order: always reindex with FEATURE_COLS.
        row = {
            'amount'               : float(amount),
            'type_TRANSFER'        : type_transfer,
            'oldbalanceOrg'        : float(old_bal_orig),
            'newbalanceOrig'       : float(new_bal_orig),
            'oldbalanceDest'       : float(old_bal_dest),
            'newbalanceDest'       : float(new_bal_dest),
            'errorBalanceOrig'     : err_orig,
            'errorBalanceDest'     : err_dest,
            'flag_orig_zero_after' : flag_orig_zero_after,
            'flag_dest_zero_before': flag_dest_zero_before,
            'flag_dest_zero_both'  : flag_dest_zero_both,
        }

        X    = pd.DataFrame([row])[FEATURE_COLS]   # enforces correct column order
        prob = float(model.predict_proba(X)[0, 1])
        flag = prob >= THRESHOLD

        # ── Results ──────────────────────────────────────────────────────────
        st.divider()
        mc1, mc2, mc3 = st.columns(3)
        mc1.metric('Fraud Probability', f'{prob:.1%}')
        mc2.metric('Decision Threshold', f'{THRESHOLD:.3f}')
        mc3.metric('Decision', '\U0001F6A8 FRAUD' if flag else '\u2705 LEGITIMATE')

        if flag:
            st.error(
                '**Transaction FLAGGED as likely fraudulent** — '
                + f'P(fraud) = {prob:.1%} >= threshold {THRESHOLD:.3f}'
            )
        else:
            st.success(
                '**Transaction CLEARED as legitimate** — '
                + f'P(fraud) = {prob:.1%} < threshold {THRESHOLD:.3f}'
            )

        # ── Feature-deviation bar chart ───────────────────────────────────────
        # Shows how each feature deviates from typical legitimate transactions,
        # normalised by the fraud-vs-legit gap.  Red = toward fraud.
        if train_stats:
            st.subheader('What drove this decision?')
            st.caption(
                'Each bar shows how far this feature deviates from a typical '
                'legitimate transaction, scaled by the fraud-vs-legit gap. '
                'Red (right) = toward fraud. Blue (left) = toward legitimate.'
            )
            legit_m = train_stats.get('legit_mean', {})
            fraud_m = train_stats.get('fraud_mean', {})
            devs, feat_labels = [], []
            for feat in FEATURE_COLS:
                lm    = legit_m.get(feat, 0)
                fm    = fraud_m.get(feat, 0)
                scale = abs(fm - lm) if abs(fm - lm) > 1e-9 else 1.0
                devs.append((row[feat] - lm) / scale)
                feat_labels.append(feat)
            colors = ['#F44336' if d > 0 else '#2196F3' for d in devs]
            fig_dev = go.Figure(go.Bar(
                x=devs, y=feat_labels, orientation='h', marker_color=colors,
            ))
            fig_dev.update_layout(
                xaxis_title='Deviation (positive = toward fraud)',
                height=400,
                margin=dict(l=10, r=10, t=10, b=10),
            )
            st.plotly_chart(fig_dev, use_container_width=True)

        # ── Engineered feature values caption ─────────────────────────────────
        st.caption(
            'Derived features — '
            + 'errorBalanceOrig: ' + f'{err_orig:,.0f}'
            + '  |  errorBalanceDest: ' + f'{err_dest:,.0f}'
            + '  |  flag_orig_zero_after: ' + str(flag_orig_zero_after)
            + '  |  flag_dest_zero_before: ' + str(flag_dest_zero_before)
            + '  |  flag_dest_zero_both: ' + str(flag_dest_zero_both)
            + '  |  type_TRANSFER: ' + str(type_transfer)
        )

    # Pre-scored example table (always visible below the form)
    if demo_df is not None:
        st.divider()
        st.subheader('Pre-scored Example Transactions')
        st.caption(
            'Sample of 100 fraud + 400 legitimate transactions, pre-scored for demo. '
            'Not representative of the real 0.13% fraud rate.'
        )
        display_cols = [c for c in ['isFraud', 'amount', 'fraud_prob', 'flagged']
                        if c in demo_df.columns]
        st.dataframe(
            demo_df[display_cols]
            .sort_values('fraud_prob', ascending=False)
            .head(20),
            use_container_width=True,
        )

# ==========================================================================
# TAB 2 — Model Performance Dashboard
# ==========================================================================
with tab2:
    st.header('Model Performance Dashboard')

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric('PR-AUC',    f"{metrics.get('pr_auc',    0):.3f}",
              help='Primary — not inflated by true negatives')
    c2.metric('ROC-AUC',   f"{metrics.get('roc_auc',   0):.3f}",
              help='Secondary — optimistic under class imbalance')
    c3.metric('F1',        f"{metrics.get('f1',        0):.3f}",
              help='Harmonic mean of precision and recall')
    c4.metric('Precision', f"{metrics.get('precision', 0):.3f}",
              help='Of flagged transactions, % actually fraudulent')
    c5.metric('Recall',    f"{metrics.get('recall',    0):.3f}",
              help='Of all real frauds, % caught at tuned threshold')

    st.divider()
    left_col, right_col = st.columns(2)

    with left_col:
        pr_path = 'reports/figures/pr_curves_comparison.png'
        if os.path.exists(pr_path):
            st.subheader('Precision-Recall Curve')
            st.image(pr_path)

        cm_found = False
        for cm_path in [
            'reports/figures/confusion_matrix_tuned_threshold.png',
            'reports/figures/confusion_matrices_before_after.png',
            'reports/figures/confusion_matrices_default_threshold.png',
        ]:
            if os.path.exists(cm_path):
                st.subheader('Confusion Matrix (threshold = ' + f'{THRESHOLD:.3f})')
                st.image(cm_path)
                cm_found = True
                break
        if not cm_found:
            st.info('Confusion matrix figure not found. Run Stages 9–10 to generate it.')

    with right_col:
        if shap_ranking and shap_mean_abs:
            st.subheader('Global Feature Importance (SHAP)')
            vals  = [shap_mean_abs.get(f, 0) for f in shap_ranking]
            fig_s = go.Figure(go.Bar(
                x=vals[::-1], y=shap_ranking[::-1],
                orientation='h', marker_color='#F44336',
            ))
            fig_s.update_layout(
                xaxis_title='Mean |SHAP Value|',
                height=420,
                margin=dict(l=10, r=10, t=10, b=10),
            )
            st.plotly_chart(fig_s, use_container_width=True)

        roc_path = 'reports/figures/roc_curves_comparison.png'
        if os.path.exists(roc_path):
            st.subheader('ROC Curve (secondary metric)')
            st.image(roc_path)

    st.divider()
    st.subheader('Why PR-AUC — Not Accuracy?')
    fraud_rate = metrics.get('fraud_rate_pct', 0.129)
    _fr_str    = str(round(fraud_rate, 3))
    _na_str    = str(round(100.0 - fraud_rate, 3))
    _base_str  = str(round(fraud_rate / 100, 4))
    st.markdown(
        "At PaySim's **" + _fr_str + '% fraud rate**, '
        + 'a model that always predicts *legitimate* for every transaction achieves **'
        + _na_str + '% accuracy** while catching **zero fraud**. '
        + 'This is the accuracy paradox — accuracy is dominated by the majority class '
        + 'and is blind to the minority you actually care about.\n\n'
        + '**PR-AUC** focuses exclusively on the positive (fraud) class. '
        + 'It cannot be inflated by correctly ignoring millions of legitimate '
        + 'transactions. Its random-baseline value equals the fraud rate itself '
        + '(~' + _base_str + '), '
        + 'so any lift above that baseline represents genuine predictive skill.'
    )

# ==========================================================================
# TAB 3 — Drift Monitor
# ==========================================================================
with tab3:
    st.header('Concept Drift Monitor')
    st.markdown(
        '**Concept drift** occurs when the statistical relationship between '
        'transaction features and the fraud label changes over time. '
        'As fraudsters adapt their tactics and customer behaviour shifts, '
        'a model trained on historical patterns can silently decay in accuracy '
        'without any visible error.\n\n'
        '_Drift was simulated by negating the strongest fraud-signal feature '
        'at the 70% mark of the temporally-ordered test stream._'
    )

    if drift_df is not None and len(drift_df) > 0:
        fig_drift = go.Figure()
        fig_drift.add_trace(go.Scatter(
            x=drift_df['idx'],
            y=drift_df['rolling_error'],
            mode='lines',
            name='Rolling Error (200-tx window)',
            line=dict(color='#2196F3', width=1.5),
        ))
        if inject_idx is not None:
            fig_drift.add_vline(
                x=inject_idx,
                line_dash='dot',
                line_color='#FF9800',
                annotation_text='Drift Injected',
                annotation_position='top left',
            )
        for ev in drift_events:
            fig_drift.add_vline(
                x=ev,
                line_dash='dash',
                line_color='#F44336',
                annotation_text='ADWIN Alert',
                annotation_position='top right',
            )
        fig_drift.update_layout(
            title='Model Error Rate Over Time — ADWIN Drift Detection',
            xaxis_title='Transaction Index (stream position)',
            yaxis_title='Rolling Error Rate',
            height=420,
            margin=dict(l=10, r=10, t=60, b=10),
        )
        st.plotly_chart(fig_drift, use_container_width=True)

        if drift_events:
            st.warning(
                '\u26a0\ufe0f **'
                + str(len(drift_events))
                + ' drift event(s) detected** at stream index: '
                + str(drift_events)
            )
            st.markdown('''**Production response playbook:**
1. **Alert** — log the detection timestamp and notify the ML team.
2. **Diagnose** — is this real concept shift, a data-pipeline bug, or a seasonal blip?
3. **Decide** — retrain only when drift is confirmed real, persistent, and fresh labelled data is available.''')
        else:
            st.info('No drift events detected in this replay.')

        with st.expander('\U0001F4CA View raw error-stream data'):
            st.dataframe(
                drift_df[['idx', 'rolling_error']].rename(columns={
                    'idx': 'Transaction Index',
                    'rolling_error': 'Rolling Error Rate',
                }),
                use_container_width=True,
            )
    else:
        st.info(
            'Drift stream data not in bundle. '
            'Re-run fraud_detection_stage13_14.ipynb to regenerate.'
        )

    st.divider()
    st.subheader('About ADWIN (Adaptive Windowing)')
    st.markdown('''
**ADWIN** (Bifet & Gavaldà, SDM 2007) maintains a variable-length sliding window
over the model's binary error stream (1 = wrong prediction, 0 = correct).

At each new transaction it asks:
*"Can I split this window into an older sub-window and a newer one whose error
rates differ by more than statistical chance (a Hoeffding bound)?"*

- **Yes** — drift detected; old sub-window dropped, window shrinks to new regime.
- **No** — stable; window grows to accumulate more statistical power.

ADWIN self-calibrates: it shrinks after detecting change and grows during stability.
It provides formal guarantees on both false-alarm and missed-detection rates,
making it more principled than a simple rolling-average threshold rule.

The `delta` parameter controls sensitivity (lower = more sensitive).
This project uses `delta=0.002`.
''')
